In [46]:
import json
import requests
import pandas as pd
import requests
from sqlalchemy import create_engine

In [47]:
# List of character
search_films = ['1','2','3', '4','5','6']

# Set url for API
url = 'https://swapi.dev/api/films/'

# Set empty lists to hold characters height and mass
Title = []
Episode_id = []
Director = []
Release_date = []
opening_crawl = []

# Loop through each character
for film in search_films:
    
    # Create search query, make request and store in json
    query = url + film
    response = requests.get(query)
    response_json = response.json()
    
    # Try to grab the height and mass of characters if they are available in the Star Wars API
    try:
        Title.append(response_json['title'])
        Episode_id.append(response_json['episode_id'])
        Director.append(response_json['director'])
        Release_date.append(response_json['release_date'])
        opening_crawl.append(response_json['opening_crawl'])
        print(f"{film} found! Appending stats")
        
    # Handle exceptions for a character that is not available in the Star Wars API
    except:
        # Append null values
        print("Film not found")
        pass

1 found! Appending stats
2 found! Appending stats
3 found! Appending stats
4 found! Appending stats
5 found! Appending stats
6 found! Appending stats

In [48]:
# Create DataFrame
starwars_films = pd.DataFrame({
    'Title' : Title,
    'Episode_id' : Episode_id,
    'Director' : Director,
    'Release_date' : Release_date,
    'opening_crawl' : opening_crawl,
})
starwars_films

,Title,Episode_id,Director,Release_date,opening_crawl
0,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [49]:
# Dependencies
from config import api_key

url = f"http://www.omdbapi.com/?apikey={api_key}&t=star+wars&y="

In [50]:
# What was the movie Gladiator rated?
movie = requests.get(url + "1999").json()
print(f'The rating of {movie["Title"]} was {movie["Rated"]}.')

The rating of Star Wars: Episode I - The Phantom Menace was PG.

In [51]:
# What was the plot of the movie Sing?
movie = requests.get(url + "1999").json()
print(f'The plot of {movie["Title"]} was: {movie["Plot"]}')

The plot of Star Wars: Episode I - The Phantom Menace was: Two Jedi escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to claim their original glory.

In [52]:
# What was the plot of the movie Sing?
movie = requests.get(url + "2002").json()
print(f'The Director of {movie["Title"]} was: {movie["Director"]}')

The Director of Star Wars: Episode II - Attack of the Clones was: George Lucas

In [53]:
# List of character
search_year = ['1977','1980','1983', '1999','2002','2005']

# Set empty lists to hold characters height and mass
Name = []
Director = []
Actors = []
Genre = []
Metascore = []
Awards = []
BoxOffice = []
Runtime = [] 
DVD_Release_Date = []

# Loop through each character
for year in search_year:
    
    # Create search query, make request and store in json
    query = url + year
    response = requests.get(query)
    response_json = response.json()
    
    # Try to grab the height and mass of characters if they are available in the Star Wars API
    try:
        Name.append(response_json['Title'])
        Director.append(response_json['Director'])
        Actors.append(response_json['Actors'])
        Genre.append(response_json['Genre'])
        Metascore.append(response_json['Metascore'])
        Awards.append(response_json['Awards'])
        BoxOffice.append(response_json['BoxOffice'])
        Runtime.append(response_json['Runtime'])
        DVD_Release_Date.append(response_json['DVD'])
        print(f"{film} found! Appending stats")
        
    # Handle exceptions for a character that is not available in the Star Wars API
    except:
        # Append null values
        print("Film not found")
        pass

6 found! Appending stats
6 found! Appending stats
6 found! Appending stats
6 found! Appending stats
6 found! Appending stats
6 found! Appending stats

In [54]:
print(url)

http://www.omdbapi.com/?apikey=3ef20ef4&t=star+wars&y=

In [55]:
# Create DataFrame
search_year = pd.DataFrame({
    'Name' : Name,
    'Director' : Director,
    'Actors' : Actors,
    'Genre' : Genre,
    'Metascore' : Metascore,
    'Awards' : Awards,
    'BoxOffice' : BoxOffice,
    'Runtime' : Runtime,
    'DVD_Release_Date' : DVD_Release_Date 
})
search_year

,Name,Director,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date
0,Star Wars,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,06 Dec 2005
1,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,21 Sep 2004
2,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,21 Sep 2004
3,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,22 Mar 2005
4,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,22 Mar 2005
5,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,01 Nov 2005

In [56]:
starwars_films

,Title,Episode_id,Director,Release_date,opening_crawl
0,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [57]:
index = pd.Index(['1', '2', '3','4','5','6'])
years = search_year.set_index(index)
years

,Name,Director,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date
1,Star Wars,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,06 Dec 2005
2,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,21 Sep 2004
3,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,21 Sep 2004
4,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,22 Mar 2005
5,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,22 Mar 2005
6,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,01 Nov 2005

In [58]:

films = starwars_films.set_index(index)
films

,Title,Episode_id,Director,Release_date,opening_crawl
1,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
2,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
3,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
4,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
5,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
6,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [59]:
merge_df = pd.merge(years, films, on=index)
merge_df

,key_0,Name,Director_x,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date,Title,Episode_id,Director_y,Release_date,opening_crawl
0,1,Star Wars,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,06 Dec 2005,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,2,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,21 Sep 2004,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,3,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,21 Sep 2004,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,4,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,22 Mar 2005,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,5,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,22 Mar 2005,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,6,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,01 Nov 2005,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [60]:
merge_df.drop(columns=['Title', 'Director_y'])

,key_0,Name,Director_x,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date,Episode_id,Release_date,opening_crawl
0,1,Star Wars,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,06 Dec 2005,4,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,2,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,21 Sep 2004,5,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,3,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,21 Sep 2004,6,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,4,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,22 Mar 2005,1,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,5,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,22 Mar 2005,2,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,6,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,01 Nov 2005,3,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [61]:
merge_df.at[0,"Name"]="Star Wars: Episode IV - A New Hope"

In [62]:
merge_df.at[0,"DVD_Release_Date"]="2005-12-06"
merge_df.at[1,"DVD_Release_Date"]="2004-09-21"
merge_df.at[2,"DVD_Release_Date"]="2004-09-21"
merge_df.at[3,"DVD_Release_Date"]="2005-03-22"
merge_df.at[4,"DVD_Release_Date"]="2005-03-22"
merge_df.at[5,"DVD_Release_Date"]="2005-11-01"
merge_df

,key_0,Name,Director_x,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date,Title,Episode_id,Director_y,Release_date,opening_crawl
0,1,Star Wars: Episode IV - A New Hope,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,2005-12-06,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,2,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,2004-09-21,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,3,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,2004-09-21,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,4,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,2005-03-22,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,5,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,2005-03-22,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,6,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,2005-11-01,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [63]:
final = merge_df.set_index("Name")
final

,key_0,Director_x,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date,Title,Episode_id,Director_y,Release_date,opening_crawl
Name,,,,,,,,,,,,,,
Star Wars: Episode IV - A New Hope,1,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,2005-12-06,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
Star Wars: Episode V - The Empire Strikes Back,2,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,2004-09-21,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
Star Wars: Episode VI - Return of the Jedi,3,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,2004-09-21,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
Star Wars: Episode I - The Phantom Menace,4,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,2005-03-22,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
Star Wars: Episode II - Attack of the Clones,5,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,2005-03-22,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
Star Wars: Episode III - Revenge of the Sith,6,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,2005-11-01,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [64]:
final.drop(columns=['key_0'])

,Director_x,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date,Title,Episode_id,Director_y,Release_date,opening_crawl
Name,,,,,,,,,,,,,
Star Wars: Episode IV - A New Hope,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,2005-12-06,A New Hope,4,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,2004-09-21,The Empire Strikes Back,5,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,2004-09-21,Return of the Jedi,6,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,2005-03-22,The Phantom Menace,1,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,2005-03-22,Attack of the Clones,2,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,2005-11-01,Revenge of the Sith,3,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [65]:
final_df = final.drop(columns=['Title','key_0','Episode_id'])

In [66]:
final_df

,Director_x,Actors,Genre,Metascore,Awards,BoxOffice,Runtime,DVD_Release_Date,Director_y,Release_date,opening_crawl
Name,,,,,,,,,,,
Star Wars: Episode IV - A New Hope,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,2005-12-06,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,2004-09-21,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,2004-09-21,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,2005-03-22,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,2005-03-22,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,2005-11-01,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [72]:
final_df = final_df.rename(columns={"DVD_Release_Date":"DVD_Released", "Release_date":"Released","opening_crawl":"Crawl", "BoxOffice":"Revenue"})
final_df

,Name,Director_x,Actors,Genre,Metascore,Awards,Revenue,Runtime,DVD_Released,Director_y,Released,Crawl
0,Star Wars: Episode IV - A New Hope,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,2005-12-06,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,2004-09-21,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,2004-09-21,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,2005-03-22,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,2005-03-22,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,2005-11-01,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [73]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          6 non-null      object
 1   Director_x    6 non-null      object
 2   Actors        6 non-null      object
 3   Genre         6 non-null      object
 4   Metascore     6 non-null      object
 5   Awards        6 non-null      object
 6   Revenue       6 non-null      object
 7   Runtime       6 non-null      object
 8   DVD_Released  6 non-null      object
 9   Director_y    6 non-null      object
 10  Released      6 non-null      object
 11  Crawl         6 non-null      object
dtypes: object(12)
memory usage: 704.0+ bytes

In [74]:
final_df

,Name,Director_x,Actors,Genre,Metascore,Awards,Revenue,Runtime,DVD_Released,Director_y,Released,Crawl
0,Star Wars: Episode IV - A New Hope,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",90,Won 6 Oscars. 63 wins & 29 nominations total,"$460,998,507",121 min,2005-12-06,George Lucas,1977-05-25,It is a period of civil war.\r\nRebel spaceshi...
1,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",82,Won 1 Oscar. 25 wins & 20 nominations total,"$292,753,960",124 min,2004-09-21,Irvin Kershner,1980-05-17,It is a dark time for the\r\nRebellion. Althou...
2,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,"Mark Hamill, Harrison Ford, Carrie Fisher","Action, Adventure, Fantasy",58,Nominated for 4 Oscars. 23 wins & 20 nominatio...,"$309,306,177",131 min,2004-09-21,Richard Marquand,1983-05-25,Luke Skywalker has returned to\r\nhis home pla...
3,Star Wars: Episode I - The Phantom Menace,George Lucas,"Ewan McGregor, Liam Neeson, Natalie Portman","Action, Adventure, Fantasy",51,Nominated for 3 Oscars. 26 wins & 69 nominatio...,"$474,544,677",136 min,2005-03-22,George Lucas,1999-05-19,Turmoil has engulfed the\r\nGalactic Republic....
4,Star Wars: Episode II - Attack of the Clones,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",54,Nominated for 1 Oscar. 19 wins & 65 nomination...,"$310,676,740",142 min,2005-03-22,George Lucas,2002-05-16,There is unrest in the Galactic\r\nSenate. Sev...
5,Star Wars: Episode III - Revenge of the Sith,George Lucas,"Hayden Christensen, Natalie Portman, Ewan McGr...","Action, Adventure, Fantasy",68,Nominated for 1 Oscar. 26 wins & 63 nomination...,"$380,270,577",140 min,2005-11-01,George Lucas,2005-05-19,War! The Republic is crumbling\r\nunder attack...

In [75]:
final_df = final_df.reset_index()

In [82]:
final_df['Released'] = pd.to_datetime(final_df['Released'])

In [83]:
final_df.to_csv("SWFilms.csv")

In [84]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         6 non-null      int64
 1   Name          6 non-null      object
 2   Director_x    6 non-null      object
 3   Actors        6 non-null      object
 4   Genre         6 non-null      object
 5   Metascore     6 non-null      object
 6   Awards        6 non-null      object
 7   Revenue       6 non-null      object
 8   Runtime       6 non-null      object
 9   DVD_Released  6 non-null      object
 10  Director_y    6 non-null      object
 11  Released      6 non-null      datetime64[ns]
 12  Crawl         6 non-null      object
dtypes: datetime64[ns](1), int64(1), object(11)
memory usage: 752.0+ bytes